# Generated by Django 3.0.2 on 2020-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200202_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='userid',
            field=models.SmallIntegerField(),
        ),
    ]
