# Generated by Django 3.0.2 on 2020-03-06 06:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('releasedate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'album',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('born', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'artist',
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'genre',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('track', models.SmallIntegerField()),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Genre')),
            ],
            options={
                'verbose_name_plural': 'song',
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reviews', models.TextField(blank=True, null=True)),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Song')),
            ],
            options={
                'verbose_name_plural': 'songreview',
                'db_table': 'songreview',
            },
        ),
        migrations.CreateModel(
            name='AlbumList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track1', models.CharField(blank=True, max_length=255, null=True)),
                ('track2', models.CharField(blank=True, max_length=255, null=True)),
                ('track3', models.CharField(blank=True, max_length=255, null=True)),
                ('track4', models.CharField(blank=True, max_length=255, null=True)),
                ('track5', models.CharField(blank=True, max_length=255, null=True)),
                ('track6', models.CharField(blank=True, max_length=255, null=True)),
                ('track7', models.CharField(blank=True, max_length=255, null=True)),
                ('track8', models.CharField(blank=True, max_length=255, null=True)),
                ('track9', models.CharField(blank=True, max_length=255, null=True)),
                ('track10', models.CharField(blank=True, max_length=255, null=True)),
                ('track11', models.CharField(blank=True, max_length=255, null=True)),
                ('track12', models.CharField(blank=True, max_length=255, null=True)),
                ('track13', models.CharField(blank=True, max_length=255, null=True)),
                ('track14', models.CharField(blank=True, max_length=255, null=True)),
                ('track15', models.CharField(blank=True, max_length=255, null=True)),
                ('albumid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Album')),
            ],
            options={
                'verbose_name_plural': 'albumlist',
                'db_table': 'albumlist',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Artist'),
        ),
    ]
