# Generated by Django 3.0.2 on 2020-03-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songreview',
            old_name='songid',
            new_name='song',
        ),
    ]
