# Generated by Django 3.0.2 on 2020-03-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20200307_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumList',
        ),
    ]
