# Generated by Django 3.0.2 on 2020-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_delete_albumlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genrename',
            field=models.CharField(max_length=255),
        ),
    ]
