# Generated by Django 3.0.2 on 2020-03-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20200308_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='songtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='reviews',
            field=models.TextField(),
        ),
    ]
